# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-04 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_wx', models.CharField(max_length=64)),
                ('photourl', models.CharField(max_length=256)),
                ('craete_time', models.DateTimeField(auto_now_add=True)),
                ('recently_time', models.DateTimeField(auto_now=True)),
                ('grade', models.IntegerField(default=0, max_length=16)),
                ('rangking', models.IntegerField(blank=True, max_length=16, null=True)),
            ],
        ),
    ]
