# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-04 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='rangking',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
