# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-07 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_auto_20180504_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photourl', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=64)),
                ('rangking', models.IntegerField(blank=True, null=True)),
                ('grade', models.IntegerField(default=0)),
                ('craete_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rangking',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='ranking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.User'),
        ),
    ]
